"""
Integrity and anti-tamper verification.
Imports hash manifest from _hashes.py (generated by _seal.py).
This file never changes after deployment, making its own hash stable.
PyInstaller: in frozen mode code-integrity checks are skipped (compiled);
             data-file checks (.license etc.) remain active.
"""

import hashlib
import logging
import os
import random
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional

from security_functions._hashes import _KA, _KB, _SM

# ── base-dir resolution (normal / Docker / PyInstaller) ──────────────────────
def _resolve_base() -> Path:
    override = os.getenv("SECURITY_DATA_DIR", "").strip()
    if override:
        return Path(override)
    if getattr(sys, "frozen", False):          # PyInstaller one-file / one-dir
        return Path(sys.executable).parent / "security_functions"
    return Path(__file__).parent

_B = _resolve_base()
_L = _B / "guard.log"
_FROZEN = getattr(sys, "frozen", False)

# ── internal logger ───────────────────────────────────────────────────────────
_il = logging.getLogger("_ig")
_il.setLevel(logging.DEBUG)
_il.propagate = False
if not _il.handlers:
    _fh = logging.FileHandler(_L, encoding="utf-8")
    _fh.setFormatter(logging.Formatter(
        "%(asctime)s  %(message)s", datefmt="%Y-%m-%dT%H:%M:%SZ"
    ))
    _il.addHandler(_fh)


# ── XOR codec ─────────────────────────────────────────────────────────────────
def _xk(i: int) -> int:
    return _KA[i % 4] ^ _KB[i % 4]


def _dc(v: List[int]) -> str:
    return bytes([b ^ _xk(i) for i, b in enumerate(v)]).hex()


# ── dynamic manifest (.chksum) ─────────────────────────────────────────────────
_DM = _B / ".chksum"


def _dm_record(names: List[str]) -> None:
    """Snapshot mutable data files on first activation."""
    existing: Dict[str, str] = {}
    if _DM.exists():
        for line in _DM.read_text(encoding="utf-8").splitlines():
            if ":" in line:
                n, rest = line.split(":", 1)
                existing[n.strip()] = rest.strip()
    for n in names:
        p = _B / n
        if p.exists():
            h = hashlib.sha256(p.read_bytes()).hexdigest()
            enc = [b ^ _xk(i) for i, b in enumerate(bytes.fromhex(h))]
            existing[n] = str(enc)
    _DM.write_text(
        "\n".join(f"{k}:{v}" for k, v in existing.items()) + "\n",
        encoding="utf-8",
    )
    try:
        _DM.chmod(0o600)
    except OSError:
        pass


def _dm_load() -> Dict[str, List[int]]:
    if not _DM.exists():
        return {}
    out: Dict[str, List[int]] = {}
    for line in _DM.read_text(encoding="utf-8").splitlines():
        if ":" not in line:
            continue
        n, rest = line.split(":", 1)
        try:
            out[n.strip()] = eval(rest.strip())  # noqa: S307
        except Exception:
            pass
    return out


# ── dummy noise ───────────────────────────────────────────────────────────────
def _noise() -> None:
    _ = sum(x * x for x in range(random.randint(80, 260)))
    time.sleep(random.uniform(0.004, 0.019))


# ── core verifier ─────────────────────────────────────────────────────────────
def _cv(path: Path, enc: List[int]) -> bool:
    if not enc:
        return True  # unsealed entry — dev mode
    if not path.exists():
        _il.error("E1 %s", path.name)
        return False
    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    if actual != _dc(enc):
        _il.error("E2 %s %s", path.name, actual[:12])
        return False
    return True


def _die() -> None:
    _il.error("E0 halt")
    # trigger destruction via dynamic import to avoid static analysis
    try:
        (lambda _m, _r: _m.trigger_self_destruct(_r))(
            __import__("security_functions._destruct", fromlist=["trigger_self_destruct"]),
            "integrity_fail",
        )
    except SystemExit:
        raise
    except Exception:
        pass
    sys.exit(1)


# ── scattered entry points ────────────────────────────────────────────────────

def _p1() -> None:
    """Subset A — called from key_store internals."""
    _noise()
    if _FROZEN:
        return   # .py checks not applicable inside compiled bundle
    for name in random.sample(["key_store.py", "__init__.py"], 2):
        if not _cv(_B / name, _SM.get(name, [])):
            _die()


def _p2() -> None:
    """Subset B — called from bot_guard internals."""
    _noise()
    if not _FROZEN:
        targets = ["bot_guard.py", "hardware_id.py"]
        random.shuffle(targets)
        for name in targets:
            if not _cv(_B / name, _SM.get(name, [])):
                _die()
    # hardware sanity cross-check (always active)
    try:
        from security_functions.hardware_id import build_hardware_id  # noqa: PLC0415
        hw = build_hardware_id()
        if not hw or len(hw) < 32:
            _il.error("E3 hw_invalid")
            _die()
    except SystemExit:
        raise
    except Exception as exc:
        _il.error("E3 hw_err %s", exc)
        _die()


def _p3() -> None:
    """Subset C — called via lambda from main.py top-level."""
    _noise()
    if _FROZEN:
        return
    if not _cv(_B / "master_key.py", _SM.get("master_key.py", [])):
        _die()


def _p4() -> None:
    """Subset D — called via eval inside start_bot()."""
    _noise()
    dyn = _dm_load()
    targets = [".license", ".salt", ".master_secret",
               "_integrity.py", "_hashes.py"]
    random.shuffle(targets)
    for name in targets:
        enc = dyn.get(name)
        if enc is None:
            continue
        if not _cv(_B / name, enc):
            _die()
